### ISSUE TITLE
HASH: Out of overflow pages.  Increase page size

### ISSUE THREAD

**Issue by Chuppa** [markcs/xml_tv#10]
Running 29 July version of YourTV and getting the above error pop up quite a few times in the log.  Not sure if it's something I need to change, or if it's the script - know nothing about Perl.  Running on MacOS 10.14.6.

Using Furl for fetching http:// and https:// requests.
Options...
region=73, output=/xml_tv/guide.xml, days = 7, fvicons = 1, Verbose = 1, pretty = 1, 

Initializing queues...
Initializing 7 worker threads...
My current directory for cachefiles is: /xml_tv
Opening Freeview cache files...
Opening Cache files...
Getting Channel list...
Getting channel list from YourTV ...
Got channel 9.yourtv.com.au - Channel Nine Sydney ...
Got channel 90.yourtv.com.au - 9HD Sydney ...
Got channel 92.yourtv.com.au - 9Gem Sydney ...
Got channel 93.yourtv.com.au - 9Go! Sydney ...
Got channel 94.yourtv.com.au - 9Life Sydney ...
Got channel 95.yourtv.com.au - 9Gem HD Sydney ...
Got channel 2.yourtv.com.au - ABC NSW ...
Got channel 20.yourtv.com.au - ABC HD NSW ...
Got channel 22.yourtv.com.au - ABC COMEDY/ABC KIDS NSW ...
Got channel 23.yourtv.com.au - ABC ME NSW ...
Got channel 24.yourtv.com.au - ABC NEWS NSW ...
Got channel 3.yourtv.com.au - SBS Sydney ...
Got channel 30.yourtv.com.au - SBS HD Sydney ...
Got channel 31.yourtv.com.au - SBS VICELAND HD NSW ...
Got channel 32.yourtv.com.au - SBS World Movies NSW ...
Got channel 33.yourtv.com.au - SBS Food NSW ...
Got channel 7.yourtv.com.au - Channel Seven Sydney ...
Got channel 70.yourtv.com.au - 7HD Sydney ...
Got channel 72.yourtv.com.au - 7TWO Sydney ...
Got channel 73.yourtv.com.au - 7mate Sydney ...
Got channel 74.yourtv.com.au - 7food network Sydney ...
Got channel 76.yourtv.com.au - 7flix NSW ...
Got channel 1.yourtv.com.au - 10 Bold Sydney ...
Got channel 10.yourtv.com.au - 10 Sydney ...
Got channel 11.yourtv.com.au - 10 Peach Sydney ...
Got channel 13.yourtv.com.au - 10 HD Sydney ...
Got channel 14.yourtv.com.au - TVSN NSW ...
Got channel 15.yourtv.com.au - SpreeTV NSW ...
Got channel 34.yourtv.com.au - NITV NSW ...
Got channel 78.yourtv.com.au - RACING.COM NSW ...
Getting EPG data...
 
Getting channel program listing for Sydney (73) for today (https://www.yourtv.com.au/api/guide/?day=today&timezone=Australia%2FSydney&format=json&region=73)...
...........
............ ........
............... .............
.................... 
................................
.......... 
..
............................... 
................................. 
........................... 
........................... ........................
............................................................... 
..
.......................................................... 
.......................... 
........................
.......... 
..
................................ ........................................ 
.
............ .......................................
 
..
...................... 
.
....................... .............................. 
......................
............. 
..
................................... 
HASH: Out of overflow pages.  Increase page size
.
.................................. 
............................
... ............................ 
.............................................. 
.
........................... ......................... .................................
..............................................................................................................
. ............................................
 
.
..................................... 

Getting channel program listing for Sydney (73) for tomorrow (https://www.yourtv.com.au/api/guide/?day=tomorrow&timezone=Australia%2FSydney&format=json&region=73)...
..............
........ .......
............... 
................................
 
........................................
 
..
................................... 
.
............................... .............................. 
.............................. ...........................................................
........................... 
HASH: Out of overflow pages.  Increase page size
.
....................................................... 
..
......................... 
................................... 
..
................................. .....................................
 
............. .......
................................ 
..
................... 
..
................... ................................. 
.................................. 
HASH: Out of overflow pages.  Increase page size
..
.................................... 
.
.................................. 
.
................................ .............................. 
.............................................. 
.............................. ......................... ........................................
........................................................................................................ 
........................................... 
..
................................. 

Getting channel program listing for Sydney (73) for thu (https://www.yourtv.com.au/api/guide/?day=thu&timezone=Australia%2FSydney&format=json&region=73)...
HASH: Out of overflow pages.  Increase page size
Getting channel program listing for Sydney (73) for fri (https://www.yourtv.com.au/api/guide/?day=fri&timezone=Australia%2FSydney&format=json&region=73)...
HASH: Out of overflow pages.  Increase page size
HASH: Out of overflow pages.  Increase page size
Getting channel program listing for Sydney (73) for sat (https://www.yourtv.com.au/api/guide/?day=sat&timezone=Australia%2FSydney&format=json&region=73)...
HASH: Out of overflow pages.  Increase page size
HASH: Out of overflow pages.  Increase page size
Getting channel program listing for Sydney (73) for sun (https://www.yourtv.com.au/api/guide/?day=sun&timezone=Australia%2FSydney&format=json&region=73)...
HASH: Out of overflow pages.  Increase page size
HASH: Out of overflow pages.  Increase page size
Getting channel program listing for Sydney (73) for mon (https://www.yourtv.com.au/api/guide/?day=mon&timezone=Australia%2FSydney&format=json&region=73)...
Processed a total of 7557 shows ...
Closing Queues...
Shutting down all threads...
Closing Cache files.
Replacing old Cache file with the new one...
Starting to build the XML...
Building the channel list...
Building the EPG list...
Finishing the XML...
Writing xmltv guide to /xml_tv/guide.xml...
Done!

**Comment by misullivan** [comment]
This is caused by using the OS X built in Perl.

If you have brew or macports installed you’ll need to change the top line of the script to your Perl path, or launch it with an explicit interpreter. E.g. “/opt/local/bin/perl ./yourtv.pl ...” etc

**Comment by Chuppa** [comment]
Same issue occurring after installing Homebrew version of Perl, and modifying script.

**Comment by misullivan** [comment]
If you didn’t, “brew install berkeley-db” .. then it should be fixed.

**Comment by Chuppa** [comment]
Same error message.

**Comment by misullivan** [comment]
Hmm that’s not right, it’s a known issue with bdb 1.x.. the brew install and new Perl interpreter should use either bdb 4.x or bob 5.x and therefore resolve it...  (bdb 1.x is compiled into one of the core libraries.. but.installing Berkeley-db should fix that if using the new interpreter.

**Comment by misullivan** [comment]
Missed the final step.. see here.. https://cwiki.apache.org/confluence/display/SPAMASSASSIN/InstallingOnMacHighSierra

**Comment by misullivan** [comment]
Fwiw I do all my dev on OS X... and don’t see this issue using macports.. but I have to specify to run /opt/local/bin/perl so I don’t get the default interpreter.

**Comment by markcs** [comment]
@Chuppa  Please confirm if you managed to get this working

**Comment by Chuppa** [comment]
Sorry guys, I haven't had time to tinker.  Quickly tried the above and same problem.

I dropped back to the previous version before the DB actions were added (think 25 July) and it is working.

I'll have another go on the weekend.

**Comment by Chuppa** [comment]
The error message is still occurring, but I've noted that fv.db is 4.41GB!!!  I've deleted that and the script runs with no errors.  Have set the file to be deleted at launch and no errors are present.

**Comment by misullivan** [comment]
That file is the cache file.  4.4G seems extra ordinarily large.. considering it’s a tied hash DB file.  It is completely replaced every run by creating a new one and copying over content that is still valid and current and adding any new entries as required.

Are you caching more than 7 days or trying to use it for multiple regions? (Because it shouldn’t get that big otherwise.)

**Comment by Chuppa** [comment]
Only 7 days, and only 1 region.  Going to try and get this running out of Docker - hopefully it sorts out the issues.

yourtv.pl --region=73 --verbose --days=7 --pretty --fvicons --output=/xml_tv/guide.xml

**Comment by Chuppa** [comment]
Works fine in Docker, so looking like a MacOS issue somewhere...  I'll close this off.
