### ISSUE TITLE
Home and Away - Australia, Canberra

### ISSUE THREAD

**Issue by gryphus0** [markcs/xml_tv#11]
Firstly - Thanks for this program guide.
Australia (Canberra) - The TV series Home and Away, the programme guide thinks it's a movie so it can't be recorded with plex.

**Comment by markcs** [comment]
okay, thanks for the report. I notice it is the same in Melbourne.  I'll look at this and report back

**Comment by markcs** [comment]
Updated and pushed a fix.  Please revert back if this solves your issue
