### ISSUE TITLE
yourTV halting on malformed JSON string

### ISSUE THREAD

**Issue by Chuppa** [markcs/xml_tv#13]
The yourTV script is erroring and halting today for Sydney due to malformed JSON.

Would be good if the script could skip the program entry and continue grabbing data instead of halting.  

There is also a new message from in the latest update: "Use of uninitialized value in substitution (s///) at /app/yourtv.pl line 400."

Using Furl for fetching http:// and https:// requests.
Options...
region=73, output=/data/guide.xml, days = 7, fvicons = 1, Verbose = 1, pretty = 1, 

Initializing queues...
Initializing 7 worker threads...
My current directory for cachefiles is: /data/cache
Opening Freeview cache files...
Opening Cache files...
Getting Channel list...
Getting channel list from YourTV ...
Got channel 9.yourtv.com.au - Channel Nine Sydney ...
Got channel 90.yourtv.com.au - 9HD Sydney ...
Got channel 92.yourtv.com.au - 9Gem Sydney ...
Got channel 93.yourtv.com.au - 9Go! Sydney ...
Got channel 94.yourtv.com.au - 9Life Sydney ...
Got channel 95.yourtv.com.au - 9Gem HD Sydney ...
Got channel 2.yourtv.com.au - ABC NSW ...
Got channel 20.yourtv.com.au - ABC HD NSW ...
Got channel 22.yourtv.com.au - ABC COMEDY/ABC KIDS NSW ...
Got channel 23.yourtv.com.au - ABC ME NSW ...
Got channel 24.yourtv.com.au - ABC NEWS NSW ...
Use of uninitialized value in substitution (s///) at /app/yourtv.pl line 400.
Got channel 3.yourtv.com.au - SBS Sydney ...
Use of uninitialized value in substitution (s///) at /app/yourtv.pl line 400.
Got channel 30.yourtv.com.au - SBS HD Sydney ...
Got channel 31.yourtv.com.au - SBS VICELAND HD NSW ...
Use of uninitialized value in substitution (s///) at /app/yourtv.pl line 400.
Got channel 32.yourtv.com.au - SBS World Movies NSW ...
Use of uninitialized value in substitution (s///) at /app/yourtv.pl line 400.
Got channel 33.yourtv.com.au - SBS Food NSW ...
Got channel 7.yourtv.com.au - Channel Seven Sydney ...
Got channel 70.yourtv.com.au - 7HD Sydney ...
Got channel 72.yourtv.com.au - 7TWO Sydney ...
Got channel 73.yourtv.com.au - 7mate Sydney ...
Got channel 74.yourtv.com.au - 7food network Sydney ...
Got channel 76.yourtv.com.au - 7flix NSW ...
Got channel 1.yourtv.com.au - 10 Bold Sydney ...
Got channel 10.yourtv.com.au - 10 Sydney ...
Got channel 11.yourtv.com.au - 10 Peach Sydney ...
Got channel 13.yourtv.com.au - 10 HD Sydney ...
Got channel 14.yourtv.com.au - TVSN NSW ...
Got channel 15.yourtv.com.au - SpreeTV NSW ...
Got channel 34.yourtv.com.au - NITV NSW ...
Use of uninitialized value in substitution (s///) at /app/yourtv.pl line 400.
Got channel 75.yourtv.com.au - Openshop ...
Got channel 78.yourtv.com.au - RACING.COM NSW ...
Getting EPG data...
 
Getting channel program listing for Sydney (73) for today (https://www.yourtv.com.au/api/guide/?day=today&timezone=Australia%2FSydney&format=json&region=73)...
................... ................... ........................ ............................. .................................. ........................ ..................... ..................... ...................................................................................... malformed JSON string, neither array, object, number, string or atom, at character offset 1 (before "assets/tv/220679_CH1...") at /app/yourtv.pl line 929.

**Comment by Chuppa** [comment]
Deleted cache files and script is proceeding as normal.

**Comment by markcs** [comment]
Pushed a fix for the uninitialised value in substitution error. Please test and comment.

**Comment by Chuppa** [comment]
Working correctly with no other messages displayed.
