### ISSUE TITLE
Option to skip certain EPG downloads

### ISSUE THREAD

**Issue by Paytah232** [markcs/xml_tv#20]
Hi. Could we get a feature (even one we have to hard code) that allows us to skip certain channels? Either by number or by name. Say I don't want any SBS channels, so might as well not parse them, so somewhere I either write "SBS" or Channels_skip=31,61,9 And it won't parse those channels?

**Comment by Schtevo66** [comment]
It's already in there - check the usage - ignore=<list of channels to ignore>

Personally though, I think it's easier to get all the channels here and just turn off the ones I don't want in the Plex DRV settings

**Comment by markcs** [comment]
> 
> 
> It's already in there - check the usage - ignore= "list of channels to ignore"
> 
> Personally though, I think it's easier to get all the channels here and just turn off the ones I don't want in the Plex DRV settings

Thanks @Schtevo66 .  I'll close this as this functionality already exists.
