### ISSUE TITLE
Ignore function doesn't exist

### ISSUE THREAD

**Issue by Paytah232** [markcs/xml_tv#21]
You closed the issue before I responded. There is no ignore option in the free_epg script.... I tried --ignore=3,32,33
and it says:
Unknown option: ignore

**Comment by Schtevo66** [comment]
Have you tried the yourtv script? It has way better data, and ignore works. 

The Free_EPG data is full of gaps, the script can't bring in data that isn't there.

**Comment by markcs** [comment]
Can you run the script with the verbose option and paste the logs?

**Comment by Paytah232** [comment]
Wasn't able to directly upload: https://mega.nz/#!ByoQTAIT!Tg_cM74uC-u3NT41ZafuPg1_zIgDTioObceJ3mAJ7jU

error.txt is the verbose log. I include the script I actually run and the output xmltv file. Hopefully it helps. Also, I entered a direct link to someone else's xmltv file https:...... and it let me through, so maybe there's some parsing error in your files now that carries through all of them???

**Comment by markcs** [comment]
@Paytah232  Is this still an issue?

**Comment by Paytah232** [comment]
Unsure, as I haven't used it in a while sorry.
________________________________

**Comment by markcs** [comment]
No worries. Please reopen a new issue if you still see this.
