### ISSUE TITLE
New errors since Jan 20

### ISSUE THREAD

**Issue by highwalker** [markcs/xml_tv#25]
There are new errors with yourtv.pl:

Use of uninitialized value in pattern match (m//) at ./yourtv.pl line 996.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at ./yourtv.pl line 985.

Using HDHomeRun Quatro in Sydney.

**Comment by markcs** [comment]
Yes, an empty response received from FreeView created this error.  Please check the update and retry

**Comment by Stuntaneous** [comment]
Also, adding Adelaide just now in xTeVe:

"xml: encoding "ISO-8859-1" declared but Decoder.CharsetReader is nil"

**Comment by markcs** [comment]
>Also, adding Adelaide just now in xTeVe: ...

@Stuntaneous 
what is xTeVe? 
Where do you see that error ?
Can you share the XML file created?

Is this a different issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Selmaks** [comment]
> 
> 
> Also, adding Adelaide just now in xTeVe:
> 
> "xml: encoding "ISO-8859-1" declared but Decoder.CharsetReader is nil"

I had the same problem.

Change 
XML->xmlDecl("ISO-8859-1")  to $XML->xmlDecl("UTF-8")
