### ISSUE TITLE
yourtv.pl error

### ISSUE THREAD

**Issue by konsumentensau** [markcs/xml_tv#26]
When I start the script, I got following message:

perl yourtv.pl --region=168
Use of uninitialized value $state in hash element at yourtv.pl line 1150.
Use of uninitialized value $state in hash element at yourtv.pl line 1151.
Freeview cache file not present/readable, this run will be slower than normal...
Cache file not present/readable, this run will be slower than normal...
Use of uninitialized value $tz in string eq at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/DateTime.pm line 2236.
Validation failed for type named NonEmptyStr declared in package Specio::Library::String (/usr/local/share/perl/5.28.1/Specio/Library/String.pm) at line 46 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named NonEmptyStr declared in package Specio::Library::String (/usr/local/share/perl/5.28.1/Specio/Library/String.pm) at line 46 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x7fffecab1120)', 'value', undef) called at (eval 289) line 82
DateTime::TimeZone::_check_new_params('name', undef) called at /usr/local/share/perl/5.28.1/DateTime/TimeZone.pm line 55
DateTime::TimeZone::new('DateTime::TimeZone', 'name', undef) called at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/DateTime.pm line 2242
DateTime::set_time_zone('DateTime=HASH(0x7f8e7eb51160)', undef) called at yourtv.pl line 849
main::toLocalTimeString('2020-02-18T23:05:00.000Z', undef) called at yourtv.pl line 617
main::getepg('Furl=REF(0x7fffed415888)', 168) called at yourtv.pl line 269

Is there something I can do about it?

Thanks in advance

**Comment by markcs** [comment]
Region 168 is Foxtel.  

The script actually doesn't support Foxtel (or Optus or Fetch), although I do realise that it prints out these 'region' during the help text.  

These providers should probably be suppressed in the help text.  I haven't looked at what is provided by yourtv or freeview for them to integrate them into the epg.

**Comment by markcs** [comment]
PayTV EPG generation will work in the latest version I think.  

to use, you need to provide your region (as normal) as well as the paytv provider 'region'.

For example
`yourtv.pl --region=73 --paytv=192` (for Sydney and Optus TV)

I haven't tested a lot, so feedback welcome.  Please raise a new issue if needed
