### ISSUE TITLE
Support for UTF-8

### ISSUE THREAD

**Issue by MCTyler** [markcs/xml_tv#28]
How can your .xml be converted into UTF-8 Format?

**Comment by Selmaks** [comment]
change $XML->xmlDecl("ISO-8859-1");  to $XML->xmlDecl("UTF-8");

**Comment by Chublo** [comment]
Any chance of UTF-8 files being made available on https://www.xmltv.net/?

**Comment by markcs** [comment]
@Chublo @MCTyler Enconding has been changed to UTF-8 in the files hosted at xmltv.net.  

What DVR application are you using?

**Comment by Chublo** [comment]
Nice one! Thank you. Using xTeve (ending up in plex) to pull together a few sources.

**Comment by markcs** [comment]
Closing this issue.  Please re-open if the change does not work.

**Comment by Chublo** [comment]
This solved it. Legend thank you.
