### ISSUE TITLE
Shepherd Integration with Plex

### ISSUE THREAD

**Issue by chris-jennings** [markcs/xml_tv#3]
I've used a Perl script with MythTV previously [https://github.com/ShephedProject/shepherd](https://github.com/ShephedProject/shepherd) and it has a lot of features that I like. It would be good if this project could leverage on the good work done with shepherd.

The guide data that Shepherd collects and reconciles is very good quality but the output format is missing some of the essential features that Plex requires (series and episode data). Adding a Plex output option to Shepherd might be a better way.

I'll have a look at it myself but I am limited for time.

Good work by the way, its a pity that Plex dropped the ball with EPG, your good work is proving invaluable for me.

**Comment by markcs** [comment]
I used to use Shephed back in the day of MythTV as well.  It was great.

I'm not sure how fully maintained Shephed is now and to be honest, I looked at it briefly, but found it easier to start from scratch.  Go ahead and merge this into Shephed if you wish!
