### ISSUE TITLE
9rush isn't in the Gold Coast guide

### ISSUE THREAD

**Issue by SCheeseman** [markcs/xml_tv#32]
I'm able to receive it, so it appears to be an omission.

**Comment by markcs** [comment]
@SCheeseman 

Can you confirm the following:

- 9rush is ch96 in GC?
- The Brisbane guide for 9rush is the same as what you get in Gold Coast?

9rush also isn't published on yourtv.com.au so that is why it is missing.

**Comment by SCheeseman** [comment]
Yes to both. Haven't had a deep look at the guide but at a glance it appears to be the same as what tvheadend snags OTA.

**Comment by markcs** [comment]
If you're getting the xml file from xmltv.net, it will be updated tomorrow (or may be later today). You will have to remap the channels in Plex.  

If you run this yourself, use the option  `--extrachannels 75-96`
