### ISSUE TITLE
Changes in Melbourne for 10HD

### ISSUE THREAD

**Issue by ozsmac** [markcs/xml_tv#33]
Firstly thank you to all who make this free EPG option available.  Hoping that someone might be able to take a look at an update for channel 1 (now 10 HD) for the Melbourne EPG.

Channel 1 is now 10 HD (as is channel 15), where the EPG is wanting to match to 10 Bold
Channel 10 is ok as 10
Channel 11 is ok as 10 PEACH
Channel 12 is ok as 10 BOLD
Channel 13 is ok as 10 SHAKE
Channel 15 is ok as 10 HD

I’m not quite sure why we need the same broadcast of channel 10 HD on channels 1 and 15, but I’m sure a good reason exists.  This wiki also confirms - https://en.wikipedia.org/wiki/List_of_digital_television_channels_in_Australia

Screen shots follow to help confirm above:

![4026484D-D873-4A32-B066-E03C41F9F50C](https://user-images.githubusercontent.com/71823638/94137569-f0236100-fea9-11ea-9df8-ab86779318c5.jpeg)
![FD820C1F-F81D-4B53-B59B-4F969157E9AC](https://user-images.githubusercontent.com/71823638/94137612-00d3d700-feaa-11ea-89b6-842929b7eb68.jpeg)
![3699F5B5-876B-4A99-8BB4-416467AE3C08](https://user-images.githubusercontent.com/71823638/94137614-029d9a80-feaa-11ea-9982-584bb3df3728.jpeg)
![F33634E1-3A90-47EB-BCE5-196B2178F8FD](https://user-images.githubusercontent.com/71823638/94137625-07fae500-feaa-11ea-989c-3e12d1ba7b5c.jpeg)

**Comment by ozsmac** [comment]
PS - work around is to simply disable channel 1 and use channel 15 for 10 HD.

**Comment by markcs** [comment]
Thanks for the report and I did notice this when remapping channels for 10 Shake.  

The data source from yourtv still has 10 Bold as channel 1.  Best is disable channel one for now as per your workaround and to wait until they have updated their data.

**Comment by markcs** [comment]
This should be fixed in the latest update.  Please refresh your guide or remap channels if required.
