### ISSUE TITLE
10 Shake (channel 13) not appearing in XML Gold Coast region 

### ISSUE THREAD

**Issue by newhollandaus** [markcs/xml_tv#35]
I re-tuned my plex HD-Homerun today and see the new channel 13 from ten as shake. But upon assigned a XML channel it has channel 13 missing.

The service is great, 

thank you very much for having this available! 🙂

![8E219524-6580-4248-8601-2DF268022458](https://user-images.githubusercontent.com/68649074/97097621-33960880-16be-11eb-8168-69013be79c42.jpeg)

**Comment by markcs** [comment]
Can you check if the channel is available at yourtv.com.au ?

**Comment by newhollandaus** [comment]
> Can you check if the channel is available at yourtv.com.au ?

Thanks for the prompt reply, no it’s not on for the Gold Coast on yourtv.com.au, it does show up for Brisbane. But not for Cairns either.

10shake does come up on https://10play.com.au/tv-guide when you select the Gold Coast.
But I’m presuming you get your data from yourtv.com.au

I could change to Brisbane EPG, but there are two 9 and 7 local news programs in the afternoon.
It might appear on yourtv.com.au in the future 🤔

**Comment by markcs** [comment]
Just checked and Shake is not available in regional areas yet.  I assume you are picking up the Brisbane Gold Coast transmission and that is why your TV can see it.  Would that be the reason?

If you run the script yourself, you can use the --extrachannels option to include Shake from Brisbane into the Gold Cost xml file.
