### ISSUE TITLE
Is data currently not working for Gold Coast?

### ISSUE THREAD

**Issue by newhollandaus** [markcs/xml_tv#40]
I’m not getting any data when doing a guide update.

`Jan 12, 2021 10:39:05.269 [0x1487875fa640] Debug — Activity: updated activity 05297893-1e57-47e0-82fd-281b59de4434 - completed 0.0% - Refreshing guide data
Jan 12, 2021 10:39:05.269 [0x1487d43e1640] Debug — EPG[xmltv]: starting full refresh for lineup(s) lineup://tv.plex.providers.epg.xmltv/http%3A%2F%2Fxmltv.net%2Fxml_files%2FGoldcoast.xml#My%20Guide
Jan 12, 2021 10:39:05.270 [0x1488018e6640] Debug — Completed: [192.168.0.36:56668] 200 POST /livetv/dvrs/5/reloadGuide (10 live) TLS GZIP 0ms 377 bytes (pipelined: 6)
Jan 12, 2021 10:39:05.956 [0x1487d43e1640] Debug — Activity: updated activity 05297893-1e57-47e0-82fd-281b59de4434 - completed 100.0% - Refreshing guide data
Jan 12, 2021 10:39:05.956 [0x1487d43e1640] Debug — Activity: updated activity 05297893-1e57-47e0-82fd-281b59de4434 - completed 100.0% - Refreshing guide data `

**Comment by newhollandaus** [comment]
It looks like it’s downloaded successfully since this morning

**Comment by markcs** [comment]
Thanks for checking!
