### ISSUE TITLE
Error on Gold Coast XML

### ISSUE THREAD

**Issue by newhollandaus** [markcs/xml_tv#42]
Gold Coast – http://xmltv.net/xml_files/Goldcoast.xml

Just a heads up, I’ve just noticed tonight on my Plex server my guide isn’t updating.

When checking the URL in a browser it’s showing displaying this error

```
This page contains the following errors:

error on line 2 at column 17: Extra content at the end of the document
Below is a rendering of the page up to the first error.
```

Sydney and others look to be working.

Very much appreciate the service guys 👍

**Comment by markcs** [comment]
Hopefully a one off XML writing error. I can see it is malformed.

Will check again after the next run.

**Comment by newhollandaus** [comment]
Thanks for the fast response, all looks good from my end now.

no stress from me having the occasional issue 👍

**Comment by markcs** [comment]
Excellent!  

Closing this issue.
