### ISSUE TITLE
404 error from your tv

### ISSUE THREAD

**Issue by copperhead57** [markcs/xml_tv#47]
i am receiving the following error

(main::getepg) Try 3: Unable to connect to https://www.yourtv.com.au/api/guide/?day=sun&timezone=Australia%2FMelbourne&format=json&region=94 (404)

**Comment by misullivan** [comment]
It would appear the API call has changed (or is currently broken)..  changing “day=sun” to “day=today” and it works.  Is there a documentation page for the API?

**Comment by misullivan** [comment]
Further poking suggests using day= only shows 3 days now ...

**Comment by copperhead57** [comment]
the feed now works for 7 days

**Comment by misullivan** [comment]
Excellent, thanks for the update Paul
