### ISSUE TITLE
yourtv.pl crashing

### ISSUE THREAD

**Issue by copperhead57** [markcs/xml_tv#48]
script crashing with
Getting epg for SBS Radio Stations ...
SBS Radio 1 ...
Error. Script died
File does not exist:  at .\yourtv.pl line 1569.

Also file from xmltv.net not being updated last day is next Wednesday.

[yourtv.log](https://github.com/markcs/xml_tv/files/7965686/yourtv.log)

**Comment by markcs** [comment]
Fixed in [latest commit](https://github.com/markcs/xml_tv/commit/2f8ed4b2bc0d393fe0c740da963303514b97aa5f)

**Comment by copperhead57** [comment]
All seems to be working
thanks
