### ISSUE TITLE
Melbourne xml data only updated to Sat 17/9

### ISSUE THREAD

**Issue by copperhead57** [markcs/xml_tv#51]
todays file only has data till sat 17/9

**Comment by markcs** [comment]
YourTV seem to be rate limiting and blocking the IP after some time which causes the script to fail.

Investing what can be done. May not be a quick fix

**Comment by 13BTurbo** [comment]
Thanks for the quick response. Hopefully you can sort it before the guide data runs out.

**Comment by vw-kombi** [comment]
I have noticed this since Tuesday.  Guide stops at midnight Sat.  Gold Coast, Brisbane, I guess all areas.

**Comment by markcs** [comment]
Are you guys able to run the script on your own?  It should not be too hard if you already have installed something like Plex

**Comment by vw-kombi** [comment]
I use emby.  The guide setup just points to an xml web page.

**Comment by 13BTurbo** [comment]
I'll give that a try.
I'm using MythTV. I might also just switch to EIT guide data for a while and see what that's like.

**Comment by copperhead57** [comment]
yesterday i was being locked out and script was crashing
this morning i rerun script for 7 days completed with no error but tv channels only loaded 2 days and some radio for 4 days

**Comment by vw-kombi** [comment]
I switched to a tvheadend plugin and EIT guide, and lost the ability to do series recordings.
This xmltv guide is the best free one.  I hope it can be fixed.
The only other option seems to be https://www.matthuisman.nz/2017/07/australia-iptv-epg-files.html - but that has no repeat flags or anything like that.

**Comment by markcs** [comment]
We have it running but slower than normal, so the guide is only updated once per day at the moment.  

Let's see how it goes and how often it fails to update
