### ISSUE TITLE
Wollongong.xml not showing new 7mate HD

### ISSUE THREAD

**Issue by saranity** [markcs/xml_tv#52]
7mate has moved channel and is now called 7mate HD.

But the Wollongong.xml still only includes the old 7 mate and all EPG entries are "Please turn to Channel 74 to continue watching 7mate."

(The Sydney.xml does contain the new 7mate HD)

**Comment by markcs** [comment]
The data is acquired from yourtv.  You can see that this is what is shown here https://www.yourtv.com.au/guide/wollongong/

Once YourTV is updated, the script will update the xml file
