### ISSUE TITLE
http://xmltv.net - melbourne

### ISSUE THREAD

**Issue by copperhead57** [markcs/xml_tv#53]
no data for thursday 15/12 onwards

**Comment by markcs** [comment]
There was a change with the regional names for FreeView, which is used for some data.  This is fixed in the latest testing branch and will be updated on xmltv.net later today.

**Comment by 13BTurbo** [comment]
Same for Hobart. Will the fix you have committed also fix other regions?

**Comment by 13BTurbo** [comment]
Thanks so much, really appreciate the service. Will check tomorrow, my system pulls the XML at 5am every morning.

**Comment by copperhead57** [comment]
@markcs thanks all fixed.
