### ISSUE TITLE
http://xmltv.net - melbourne

### ISSUE THREAD

**Issue by copperhead57** [markcs/xml_tv#55]
no data for friday 3rd march onwards

**Comment by ClintonLangerakPAVS** [comment]
Same for Hobart. Nothing past 6am Thu 2/3

**Comment by 13BTurbo** [comment]
Same for Hobart. No data beyond ~6am Thu 2/3.

**Comment by 13BTurbo** [comment]
Actually it was a change in xmltv channel id from yourtv.com.au to auepg.com.au that was messing with my system. Guide data for Hobart okay to 5/3 now.

**Comment by copperhead57** [comment]
change to auepg.com.au also messin with my system
Closing issue
