### ISSUE TITLE
xmltv.net Hobart no data beyond 5/3

### ISSUE THREAD

**Issue by 13BTurbo** [markcs/xml_tv#57]
It seems yourtv.com.au has dropped Tasmania as a region?

If I run yourtv.pl with region 88 I get a 502 error. (region 94, Melbourne works okay).
Running free_epg.pl only retrieves SBS and ABC guide data.

How can I get the commercial channels for Tas from freeview with free_epg.pl?

**Comment by misullivan** [comment]
Please see http://xmltv.net/ and have a read.. mappings and regions have been updated.

Leave a message in the comments there if you are downloading a ready made file, otherwise if you're generating your own files, and it still fails, please re-comment.

Regards,

Michelle

**Comment by 13BTurbo** [comment]
Thanks Michelle,

I've been using the ready made files.
When this issue arose, I tried using the scripts directly and was encountering the 502 error as reported in issue #61 

Hobart file on xmltv.net now has 7 days of data, but no descriptions.

Closing this issue as it seems to be related.

**Comment by markcs** [comment]
> Thanks Michelle,
> 
> I've been using the ready made files.
> When this issue arose, I tried using the scripts directly and was encountering the 502 error as reported in issue #61 
> 
> Hobart file on xmltv.net now has 7 days of data, but no descriptions.
> 
> Closing this issue as it seems to be related.

Remap the channels in Plex and it should be fine

**Comment by 13BTurbo** [comment]
Thanks Mark,

Not using Plex, using MythTV. Have 7 days of guide, just no description/blurb for the programs. (no <desc> field in generated XML)

**Comment by markcs** [comment]
This will be fixed in the next release.
