### ISSUE TITLE
xmltv.net Melbourne no data beyond 5/3

### ISSUE THREAD

**Issue by copperhead57** [markcs/xml_tv#58]
no data with a start date for monday 6th march onwards

**Comment by misullivan** [comment]
Please see http://xmltv.net/ and have a read.. mappings and regions have been updated.

Leave a message in the comments there if you are downloading a ready made file, otherwise if you're generating your own files, and it still fails, please re-comment.

Regards,

Michelle

**Comment by copperhead57** [comment]
ready made

**Comment by copperhead57** [comment]
file http://xmltv.net/xml_files/Melbourne.xml this morning (4 march) still has no data beyond 5/3.

**Comment by markcs** [comment]
@copperhead57  Please refer to #61 as a catch-all issue tracker for this problem
