### ISSUE TITLE
guide data is missing the next 16 hours

### ISSUE THREAD

**Issue by matthuisman** [markcs/xml_tv#60]
eg.
http://xmltv.net/xml_files/Sydney.xml
10auepg.com.au

earliest program is
<programme start="20230303230000 +0000" stop="20230304010000 +0000" channel="10auepg.com.au">
<title>Studio 10: Saturday</title>

as of writing, its 6pm in NSW on Friday (03/03/23)
Above program is starting at 11pm utc 03/03/23 = 10am 04/03/23 NSW
So, thats 16 hours away

It was the same yesterday as well.

Maybe the scraper just needs a -1 to start from a day earlier :)
Or, the API's being used are UTC time and the script using AU time

PS: 
Great respect for your scrapers :) 
i moved my generated epgs to use yours for AU channels some time back.
I do have <tv source-info-name="matthuisman.nz, xmltv.net, nzxmltv.com">
Let me know if you want some other sort of credit or the above renamed :)

**Comment by oismacca** [comment]
Seconded. Mad respect for this project. The xmltv.net files are the only good resource available out there. Wouldn't be possible if not for this project so thank you!

**Comment by markcs** [comment]
#61
