### ISSUE TITLE
xml files missing guide data

### ISSUE THREAD

**Issue by markcs** [markcs/xml_tv#61]
This is a generic issue to cover the problem we are facing at the moment.  There are issues with scraping data from yourtv due to rate limiting and possibly IP blocking, so we are looking for another solution.  We had one from TelstraTV, but they announced that this will not continue and if you look online, you'll see that the epg is not being updated (ie [](https://media.telstra.com.au/epgtvguide.html)).

I've got another solution that I'm working on.  If you want to test out some early xml, please let me know.

**Comment by waynethomas69** [comment]
I'm happy to test some early xml

**Comment by misullivan** [comment]
it is rate limiting and some backend issues.

They have moved to akami which means they have IPv4 and IPv6 available - however Furl won't use IPv6 at the moment.   There are 2 errors when downloading you can see:

'502' errors which are temporary and stopping the scripts from processing.
'403' errors which are applied to rate limit.. if you trigger this it will ban your IP for around 60 minutes.

This is an example of the rate limiting:

Getting channel program listing for Wollongong (71) for today ...
.......................... ........................ ............................... .......................... ................................... ...................... ...................... .............................................................................. ........................................... ............................................ ................................. ................................. ............................. ............. ............................................
5: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140830413 (403)

4: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140830414 (403)
 
Unable to connect to YourTV for https://www.yourtv.com.au/api/airings/140830413 ... skipping  (200)

Unable to connect to YourTV for https://www.yourtv.com.au/api/airings/140830414 ... skipping  (200)
........
10: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833350 (403)

2: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833352 (403)

8: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833354 (403)

3: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833351 (403)

1: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833358 (403)

7: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833355 (403)

9: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833357 (403)

6: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140833356 (403)
^C
isux:xml_tv michelle$ /opt/local/bin/perl5.30 ./yourtv.pl -verbose  --region=71 --output your.xml --config configs/regional.conf 
Using Furl for fetching http:// and https:// requests.
(main::buildregions) Try 1: Unable to connect to https://www.yourtv.com.au/guide/ (403)
(main::buildregions) Try 2: Unable to connect to https://www.yourtv.com.au/guide/ (403)

This shows the 502s:

Getting channel program listing for Wollongong (71) for tomorrow ...
.......................... ................................ ................................. .......................... ............................... ...................... ......................+ ................................
5: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140825230 (502)
.............
3: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140825251 (502)
.
4: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140825256 (502)
....
2: Thread Fetch FAILED for: https://www.yourtv.com.au/api/airings/140825255 (502)
....
 
I have been modifying the script over night and have successfully got it to download all the data.. however based on how it's rate limited and what my mods do I would avoid posting it publicly for fear of the API getting completely shut down.

Part of the issue will be resolved by running the scripts on multiple hosts to enable multiple IPs.

Second thing we should do is make an 'airings cache' that can be used by multiple region runs...  or make a new version that gets all regions at the same time and builds all of them at the same time (would require extensive work.)

Regards,

Michelle

**Comment by matthuisman** [comment]
did you used to use fvau-api-prod.switch.tv ?
is that no longer suitable?

**Comment by markcs** [comment]
> did you used to use fvau-api-prod.switch.tv ? is that no longer suitable?

Yes, that is available, still used for some parts, but the data there is not great.

**Comment by markcs** [comment]
> I'm happy to test some early xml

Which city/state?

**Comment by markcs** [comment]
Thanks @oismacca 

XML files are updated on xmltv.net.

Plex mappings will have to be redone. 

I'm sure there are missing channels, but this can be rectified later

**Comment by matthuisman** [comment]
any reason you cant just use the lcn as the channel id so it doesnt change between services?

**Comment by Spin35** [comment]
I'm still getting data from OzTivo through my old epgstream.net XMLTV Download app.  I wonder if this might be an alternative source.  The channel list has not been updated but the programme data is still getting updated.  
It looks like its been forgotten and left to run.
[ServiceDirectory.xml.txt](https://github.com/markcs/xml_tv/files/10908739/ServiceDirectory.xml.txt)
[http://www.oztivo.net/twiki/bin/view](http://www.oztivo.net/twiki/bin/view)
[https://hd.oztivo.net/tivo-bin/tvguide.pl](https://hd.oztivo.net/tivo-bin/tvguide.pl)

**Comment by NoTan2** [comment]
Are there any plans to restore the "Description" <desc> data into the files?

**Comment by markcs** [comment]
> Are there any plans to restore the "Description" <desc> data into the files?

Yes. This is fixed in code. The guy managing the site is away and back later this week, when it will be updated.

**Comment by NoTan2** [comment]
> > Are there any plans to restore the "Description"  data into the files?
> 
> Yes. This is fixed in code. The guy managing the site is away and back later this week, when it will be updated.

Thank you. Much appreciated.

**Comment by waynethomas69** [comment]
> 

Sorry, missed your response. I'm currently using Sydney again so imagine you don't need any early testing any more.

**Comment by NoTan2** [comment]
> > Are there any plans to restore the "Description"  data into the files?
> 
> Yes. This is fixed in code. The guy managing the site is away and back later this week, when it will be updated.

The Description is back in the files now. Once again, Thank you.

**Comment by markcs** [comment]
xml files are up and working again on xmltv.net.  Please re-open a new issue if there are problems
