### ISSUE TITLE
Channel 85 missing

### ISSUE THREAD

**Issue by gregeeh** [markcs/xml_tv#62]
Hi,

I've noticed GEMHD Channel 85 is missing from the Central Coast listing.  Any chance of having this added?

TIA

**Comment by markcs** [comment]
Checking the xml files, Central Coast has Gem HD on channel 95.  Do you also have it on 85 ?

**Comment by gregeeh** [comment]
Looking at my HDHomeRun it shows Channel 85 has 9GEM Central Coast and Channel 95 as 9GEM Sydney.

https://i.imgur.com/CRIsR3o.jpeg

**Comment by markcs** [comment]
> Looking at my HDHomeRun it shows Channel 85 has 9GEM Central Coast and Channel 95 as 9GEM Sydney.
> 
> https://i.imgur.com/CRIsR3o.jpeg

This should hopefully be mapped now. We are assuming that 95 and 85 have the same programs? Can you check and confirm?
