### ISSUE TITLE
EPG for live streaming channel

### ISSUE THREAD

**Issue by R0B3r7p** [markcs/xml_tv#70]
Is it possible to get the epg data for live streaming channel MovieSphere or others?

All data is available for MovieSphere on the online guide of Fetchtv but I have not been able to download the EPG after trying a few different regions.

**Comment by markcs** [comment]
Is MovieSphere a free to air channel ?  This EPG is only for FTA channels

**Comment by R0B3r7p** [comment]
It is free streaming channel available on 10play and 7plus.

**Comment by markcs** [comment]
okay, if it is not a Free To Air channel (ie broadcast TV), then it won't be included in this EPG.  

You could try https://www.matthuisman.nz/2019/01/live-au-iptv-channels-on-android.html

**Comment by R0B3r7p** [comment]
ok, no worries. 
If I know the channel id and the data is available on  fetchtv epg programslist?channel_ids=2406
Is there a command I can give to download and process the data for a single channel?

**Comment by markcs** [comment]
> ok, no worries. 
> If I know the channel id and the data is available on  fetchtv epg programslist?channel_ids=2406
> Is there a command I can give to download and process the data for a single channel?

No. Sorry.
